using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Collections.Generic;
using LlmTornado.Agents.Dnd.FantasyEngine.DataModels;


namespace LlmTornado.Agents.Dnd.Utility;

// File: Program.cs
// Target: .NET 7+ (or .NET Core 3.1+)
// Usage: dotnet run -- <path-to-adventure.json>
// Output: adventure.dot and adventure.png (if dot.exe found)


public class AdventureViewer
{
    public readonly string AdventurePath;

    public AdventureViewer(string adventurePath)
    {
        AdventurePath = adventurePath;
    }

    public int Build()
    {
        string jsonPath = AdventurePath;
        if (!File.Exists(jsonPath))
        {
            Console.WriteLine($"File not found: {jsonPath}");
            return 2;
        }

        var json = File.ReadAllText(jsonPath);
        var opts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        opts.Converters.Add(new JsonStringEnumConverter());
        var doc = JsonSerializer.Deserialize<JsonDocument>(json, opts);

        // read Locations array
        var root = doc.RootElement;
        if (!root.TryGetProperty("Locations", out var locationsElem))
        {
            Console.WriteLine("No 'Locations' array found in JSON.");
            return 3;
        }

        var locations = new List<FantasyLocation>();
        foreach (var locEl in locationsElem.EnumerateArray())
        {
            var loc = new FantasyLocation
            (
                id: locEl.GetProperty("Id").GetString(),
                name: locEl.TryGetProperty("Name", out var n) ? n.GetString() : null,
                description: locEl.TryGetProperty("Description", out var d) ? d.GetString() : null,
                restLocation: locEl.TryGetProperty("RestLocation", out var r) && r.GetBoolean(),
                routes: locEl.TryGetProperty("Routes", out var routesEl) ? routesEl.EnumerateArray().Select(re => new FantasyRoute
                (
                    toLocationId: re.TryGetProperty("EndingLocationId", out var end) ? end.GetString() : null,
                    description: re.TryGetProperty("Description", out var desc) ? desc.GetString() : null,
                    distanceInHours: re.TryGetProperty("DistanceInHours", out var dist) ? dist.GetInt32() : 0
                )).ToArray() : Array.Empty<FantasyRoute>()
            );

           
            locations.Add(loc);
        }

        // Build DOT
        string dotPath = Path.Combine(Path.GetDirectoryName(jsonPath) ?? ".", "adventure.dot");
        using (var w = new StreamWriter(dotPath, false))
        {
            w.WriteLine("// Generated by adventure-dot-generator");
            w.WriteLine("digraph Adventure {");
            w.WriteLine("  rankdir=LR;");                     // left-to-right layout
            w.WriteLine("  node [shape=ellipse, style=filled, fillcolor=\"/paired12/2\", fontname=\"Segoe UI\"];");

            // Add nodes with labels, color rest locations differently
            foreach (var loc in locations)
            {
                string label = EscapeDotLabel(string.IsNullOrEmpty(loc.Name) ? loc.Id : $"{loc.Name}\\n({loc.Id})");
                if (loc.CanRestHere)
                {
                    w.WriteLine($"  \"{loc.Id}\" [label=\"{label}\", fillcolor=lightgoldenrodyellow, shape=oval];");
                }
                else
                {
                    w.WriteLine($"  \"{loc.Id}\" [label=\"{label}\"];");
                }
            }

            // Add edges
            foreach (var loc in locations)
            {
                if (loc.Routes == null) continue;
                foreach (var r in loc.Routes.Where(x => !string.IsNullOrEmpty(x.ToLocationId)))
                {
                    // optionally include description as tooltip
                    var label = string.IsNullOrEmpty(r.Description) ? "" : $" [tooltip=\"{EscapeDotLabel(r.Description)}\"]";
                    w.WriteLine($"  \"{loc.Id}\" -> \"{r.ToLocationId}\"{label};");
                }
            }

            w.WriteLine("}");
        }

        Console.WriteLine($"DOT written to: {dotPath}");

        // Try to call Graphviz to produce PNG if dot is available
        string pngPath = Path.Combine(Path.GetDirectoryName(jsonPath) ?? ".", "adventure.png");
        try
        {
            var psi = new ProcessStartInfo("dot", $"-Tpng \"{dotPath}\" -o \"{pngPath}\"")
            {
                CreateNoWindow = true,
                UseShellExecute = false
            };
            var p = Process.Start(psi);
            p.WaitForExit(5000);
            if (File.Exists(pngPath))
            {
                Console.WriteLine($"PNG rendered to: {pngPath}");
            }
            else
            {
                Console.WriteLine("Graphviz 'dot' ran but PNG not found. You can run:");
                Console.WriteLine($"  dot -Tpng \"{dotPath}\" -o \"{pngPath}\"");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Graphviz not found or failed to run. To render the PNG manually, install Graphviz and run:");
            Console.WriteLine($"  dot -Tpng \"{dotPath}\" -o \"{pngPath}\"");
#if DEBUG
            Console.WriteLine("Exception: " + ex);
#endif
        }

        return 0;
    }

    static string EscapeDotLabel(string s)
    {
        if (s == null) return "";
        // Escape quotes and newlines for DOT label
        return s.Replace("\"", "\\\"").Replace("\r", "").Replace("\n", "\\n");
    }
}